/**
 * Symbol definitions for slot game
 * Each symbol has id, name, icon (emoji/char), colors, and payout multipliers
 */

export const SYMBOLS = {
  WILD: {
    id: "WILD",
    name: "Wild",
    icon: "⭐",
    color: "#FFD700",
    bg: "linear-gradient(135deg, #8B4500, #FFD700, #8B4500)",
    mult: [0, 0, 100, 500, 2500], // [2-of-kind, 3, 4, 5]
    wild: true,
  },
  SEVEN: {
    id: "SEVEN",
    name: "Seven",
    icon: "7",
    color: "#FFD700",
    bg: "linear-gradient(135deg, #8B0000, #DC143C, #8B0000)",
    mult: [0, 0, 50, 200, 1000],
  },
  BAR: {
    id: "BAR",
    name: "Bar",
    icon: "BAR",
    color: "#FFFFFF",
    bg: "linear-gradient(135deg, #1a1a2e, #333, #1a1a2e)",
    mult: [0, 0, 25, 100, 500],
  },
  BELL: {
    id: "BELL",
    name: "Bell",
    icon: "🔔",
    color: "#FFD700",
    bg: "linear-gradient(135deg, #4a0030, #8b0060, #4a0030)",
    mult: [0, 0, 15, 50, 200],
  },
  CHERRY: {
    id: "CHERRY",
    name: "Cherry",
    icon: "🍒",
    color: "#FFFFFF",
    bg: "linear-gradient(135deg, #600, #cc0033, #600)",
    mult: [0, 5, 10, 30, 150],
  },
  LEMON: {
    id: "LEMON",
    name: "Lemon",
    icon: "🍋",
    color: "#FFFFFF",
    bg: "linear-gradient(135deg, #3a5000, #6b8e00, #3a5000)",
    mult: [0, 3, 8, 25, 100],
  },
  ORANGE: {
    id: "ORANGE",
    name: "Orange",
    icon: "🍊",
    color: "#FFFFFF",
    bg: "linear-gradient(135deg, #803000, #cc5500, #803000)",
    mult: [0, 2, 6, 20, 75],
  },
  PLUM: {
    id: "PLUM",
    name: "Plum",
    icon: "🍑",
    color: "#FFFFFF",
    bg: "linear-gradient(135deg, #400060, #7a00b3, #400060)",
    mult: [0, 0, 5, 15, 50],
  },
  MELON: {
    id: "MELON",
    name: "Melon",
    icon: "🍉",
    color: "#FFFFFF",
    bg: "linear-gradient(135deg, #004d00, #008000, #004d00)",
    mult: [0, 0, 4, 12, 40],
  },
  GRAPES: {
    id: "GRAPES",
    name: "Grapes",
    icon: "🍇",
    color: "#FFFFFF",
    bg: "linear-gradient(135deg, #1a003a, #4a0080, #1a003a)",
    mult: [0, 0, 3, 10, 30],
  },
};

export const SYMBOL_KEYS = Object.keys(SYMBOLS);

// Reel strips (virtual reels)
export const REEL_STRIPS = [
  // Reel 1
  [
    "SEVEN",
    "CHERRY",
    "LEMON",
    "BAR",
    "ORANGE",
    "PLUM",
    "WILD",
    "GRAPES",
    "BELL",
    "MELON",
    "CHERRY",
    "LEMON",
    "BAR",
    "ORANGE",
    "SEVEN",
    "PLUM",
    "BAR",
    "CHERRY",
    "LEMON",
    "MELON",
    "ORANGE",
    "BELL",
    "GRAPES",
    "CHERRY",
    "LEMON",
    "SEVEN",
    "BAR",
    "ORANGE",
    "PLUM",
    "WILD",
  ],
  // Reel 2
  [
    "BAR",
    "LEMON",
    "CHERRY",
    "SEVEN",
    "ORANGE",
    "BELL",
    "PLUM",
    "CHERRY",
    "LEMON",
    "MELON",
    "BAR",
    "GRAPES",
    "CHERRY",
    "ORANGE",
    "WILD",
    "LEMON",
    "SEVEN",
    "BELL",
    "CHERRY",
    "PLUM",
    "LEMON",
    "BAR",
    "ORANGE",
    "MELON",
    "CHERRY",
    "GRAPES",
    "SEVEN",
    "LEMON",
    "ORANGE",
    "BAR",
  ],
  // Reel 3
  [
    "ORANGE",
    "SEVEN",
    "BELL",
    "CHERRY",
    "LEMON",
    "BAR",
    "MELON",
    "CHERRY",
    "GRAPES",
    "ORANGE",
    "WILD",
    "LEMON",
    "SEVEN",
    "CHERRY",
    "PLUM",
    "BAR",
    "ORANGE",
    "LEMON",
    "BELL",
    "CHERRY",
    "MELON",
    "SEVEN",
    "LEMON",
    "BAR",
    "GRAPES",
    "CHERRY",
    "ORANGE",
    "LEMON",
    "PLUM",
    "SEVEN",
  ],
  // Reel 4
  [
    "CHERRY",
    "LEMON",
    "BAR",
    "ORANGE",
    "SEVEN",
    "PLUM",
    "CHERRY",
    "BELL",
    "LEMON",
    "MELON",
    "BAR",
    "GRAPES",
    "CHERRY",
    "ORANGE",
    "WILD",
    "LEMON",
    "SEVEN",
    "CHERRY",
    "PLUM",
    "LEMON",
    "BAR",
    "ORANGE",
    "BELL",
    "CHERRY",
    "GRAPES",
    "SEVEN",
    "LEMON",
    "CHERRY",
    "ORANGE",
    "BAR",
  ],
  // Reel 5
  [
    "LEMON",
    "SEVEN",
    "CHERRY",
    "BAR",
    "ORANGE",
    "BELL",
    "PLUM",
    "CHERRY",
    "LEMON",
    "MELON",
    "WILD",
    "GRAPES",
    "CHERRY",
    "BAR",
    "ORANGE",
    "SEVEN",
    "LEMON",
    "BELL",
    "CHERRY",
    "PLUM",
    "LEMON",
    "BAR",
    "ORANGE",
    "SEVEN",
    "CHERRY",
    "GRAPES",
    "LEMON",
    "BELL",
    "CHERRY",
    "BAR",
  ],
];

// Get a random symbol
export function randomSymbol() {
  return SYMBOL_KEYS[Math.floor(Math.random() * SYMBOL_KEYS.length)];
}
